apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: frontend 
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: carmenzz/group-3-project-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: "KAFKA_BOOTSTRAP_SERVERS"
          value: "kafka.default.svc.cluster.local:9092"
        imagePullPolicy: Always