package_update: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - git

runcmd:
  - |
    # Add Docker's official GPG key:
    apt-get update
    apt-get install ca-certificates curl -y
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc

    # Add the repository to Apt sources:
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update
    apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

    export K3S_TOKEN="${K3S_TOKEN}"
    curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 --cluster-init --token "${K3S_TOKEN}"
    until kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml get nodes; do echo "Waiting for Kubernetes API..."; sleep 10; done

    export PATH=$PATH:/usr/local/bin
    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
    export HELM_KUBECONFIG=/etc/rancher/k3s/k3s.yaml
    chmod 600 /etc/rancher/k3s/k3s.yaml
    chown ubuntu:ubuntu /etc/rancher/k3s/k3s.yaml
    echo "export PATH=$PATH:/usr/local/bin" >> /home/ubuntu/.bashrc
    echo "export KUBECONFIG=/etc/rancher/k3s/k3s.yaml" >> /home/ubuntu/.bashrc
    echo "export HELM_KUBECONFIG=/etc/rancher/k3s/k3s.yaml" >> /home/ubuntu/.bashrc

    curl -Lo k9s.tar.gz https://github.com/derailed/k9s/releases/download/v0.28.1/k9s_Linux_amd64.tar.gz
    tar -xzf k9s.tar.gz
    mv k9s /usr/local/bin/
    chmod +x /usr/local/bin/k9s
    echo "alias k9s='sudo KUBECONFIG=/etc/rancher/k3s/k3s.yaml k9s'" >> /home/ubuntu/.bashrc


    k9s version

    kubectl apply -f https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/master/manifests/controller-manager/cloud-controller-manager-roles.yaml
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/master/manifests/controller-manager/cloud-controller-manager-role-bindings.yaml
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/master/manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml

    kubectl get pvc -A

    curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    helm repo add cpo https://kubernetes.github.io/cloud-provider-openstack
    helm repo add bitnami https://charts.bitnami.com/bitnami
  
    helm upgrade --install mongo bitnami/mongodb

    export chartsdir=/home/ubuntu/charts
    while [[ ! -d "$chartsdir" ]]; do
      echo "Waiting for directory: $chartsdir"
      sleep 1  # Wait for 1 second before checking again
    done

    chmod +x $chartsdir/simulator/install-min-io.sh
    $chartsdir/simulator/install-min-io.sh

    chmod +x $chartsdir/simulator/create-service-account.sh
    $chartsdir/simulator/create-service-account.sh

    chmod +x $chartsdir/kafka/start-kafka.sh
    $chartsdir/kafka/start-kafka.sh

    helm upgrade --install backend $chartsdir/backend --values $chartsdir/backend/values.yaml

    echo "Public IP = ${PUBLIC_IP}"

    helm upgrade --install --set publicmasterip="${PUBLIC_IP}" frontend $chartsdir/frontend --values $chartsdir/frontend/values.yaml

    ip_address=$(ip addr show | grep -oE '10\.10\.[0-9]+\.[0-9]+/16' | cut -d '/' -f 1)
    helm upgrade --install --set localmasterip="$ip_address" simulator $chartsdir/simulator


# Logging
output: { all: '| tee -a /home/ubuntu/cloud-init-output.log' }