apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: backend 
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: makenjoy/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: "KAFKA_BOOTSTRAP_SERVERS"
          value: "kafka.default.svc.cluster.local:9092"
        imagePullPolicy: Always
