replicaCount: 2

image:
  repository: makenjoy/backend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  host: backend.example.com
  path: /

envVars:
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: kafka.default.svc.cluster.local:9092

resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "500m"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
