replicaCount: 1

image:
  # repository: carmenzz/group-3-project-backend
  repository: makenjoy/backend
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 8000

ingress:
  # enabled: true
  enabled: false
  host: backend.example.com
  path: /

envVars:
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: kafka.default.svc.cluster.local:9092
  - name: MONGO_HOSTNAME
    value: mongo-mongodb.default.svc.cluster.local
  - name: MONGO_INITDB_ROOT_USERNAME 
    value: myuser
  - name: MONGO_INITDB_ROOT_PASSWORD
    value: secret
  - name: MONGO_HOST
    value: mongo