replicaCount: 1

image:
  repository: makenjoy/backend
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 8000

ingress:
  # enabled: true
  enabled: false
  host: backend.example.com
  path: /

envVars:
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: kafka.default.svc.cluster.local:9092
